<!DOCTYPE html>
<html>
<head>
    <title>Category Form</title>
    <style>
        .admin__actions-toolbar {
            text-align: center;
        }

        .empty-space {
            height: 20px; /* Adjust the height as needed */
        }
    </style>
</head>
<body>
    <?php /** @var Myvendor\Faqs\Block\Adminhtml\CategoryAdd $block */ ?>
    <div class="admin__fieldset">
        <legend class="admin__legend"><span><?='FAQ Information' ?></span></legend>
        <form action="<?php echo $block->getFormAction() ?>" method="post" class="form-container">
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />

            <div class="admin__field">
                <label class="admin__field-label"><?='Category Name' ?></label>
                <div class="admin__field-control">
                    <input type="text" name="category_name" class="admin__control-text" required>
                </div>
            </div>
            <div class="admin__actions-toolbar">
                <div class="admin__actions">
                    <button type="submit" class="action-primary"><?= __('Save') ?></button>
                </div>
                <div class="empty-space"></div> <!-- This creates the empty space -->
            </div>
        </form>
    </div>
</body>
</html>
